// Mocks generated by Mockito 5.4.6 from annotations
// in e_healty/test/providers/auth/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i15;

import 'package:e_healty/data/datasources/firebase_auth_datasource.dart'
    as _i23;
import 'package:e_healty/data/models/aktivitas_model.dart' as _i10;
import 'package:e_healty/data/models/user_model.dart' as _i7;
import 'package:e_healty/data/repositories/aktivitas_repository.dart' as _i2;
import 'package:e_healty/data/repositories/auth_repository.dart' as _i6;
import 'package:e_healty/data/repositories/tips_kesehatan_repository.dart'
    as _i4;
import 'package:e_healty/domain/entities/tips_kesehatan.dart' as _i5;
import 'package:e_healty/domain/entities/user.dart' as _i3;
import 'package:e_healty/domain/usecase/aktivitas_sehat/create_aktivitas.dart'
    as _i8;
import 'package:e_healty/domain/usecase/aktivitas_sehat/delete_aktivitas.dart'
    as _i13;
import 'package:e_healty/domain/usecase/aktivitas_sehat/get_aktivitas.dart'
    as _i11;
import 'package:e_healty/domain/usecase/aktivitas_sehat/update_aktivitas.dart'
    as _i12;
import 'package:e_healty/domain/usecase/auth/login.dart' as _i19;
import 'package:e_healty/domain/usecase/auth/logout.dart' as _i21;
import 'package:e_healty/domain/usecase/auth/register.dart' as _i20;
import 'package:e_healty/domain/usecase/auth/update_photo.dart' as _i22;
import 'package:e_healty/domain/usecase/tips_kesehatan/get_tips_kesehatan.dart'
    as _i17;
import 'package:e_healty/domain/usecase/tips_kesehatan/get_tips_kesehatan_detail.dart'
    as _i18;
import 'package:e_healty/presentation/providers/auth_provider.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAktivitasRepository_0 extends _i1.SmartFake
    implements _i2.AktivitasRepository {
  _FakeAktivitasRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTipsKesehatanRepository_2 extends _i1.SmartFake
    implements _i4.TipsKesehatanRepository {
  _FakeTipsKesehatanRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTipsKesehatanEntity_3 extends _i1.SmartFake
    implements _i5.TipsKesehatanEntity {
  _FakeTipsKesehatanEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_4 extends _i1.SmartFake
    implements _i6.AuthRepository {
  _FakeAuthRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_5 extends _i1.SmartFake implements _i7.UserModel {
  _FakeUserModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreateAktivitas].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAktivitas extends _i1.Mock implements _i8.CreateAktivitas {
  MockCreateAktivitas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AktivitasRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeAktivitasRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.AktivitasRepository);

  @override
  _i9.Future<void> call(_i10.AktivitasModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#call, [m]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [GetAktivitas].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAktivitas extends _i1.Mock implements _i11.GetAktivitas {
  MockGetAktivitas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AktivitasRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeAktivitasRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.AktivitasRepository);

  @override
  _i9.Future<List<_i10.AktivitasModel>> call(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#call, [uid]),
            returnValue: _i9.Future<List<_i10.AktivitasModel>>.value(
              <_i10.AktivitasModel>[],
            ),
          )
          as _i9.Future<List<_i10.AktivitasModel>>);
}

/// A class which mocks [UpdateAktivitas].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAktivitas extends _i1.Mock implements _i12.UpdateAktivitas {
  MockUpdateAktivitas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AktivitasRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeAktivitasRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.AktivitasRepository);

  @override
  _i9.Future<void> call(_i10.AktivitasModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#call, [m]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [DeleteAktivitas].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAktivitas extends _i1.Mock implements _i13.DeleteAktivitas {
  MockDeleteAktivitas() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AktivitasRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeAktivitasRepository_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.AktivitasRepository);

  @override
  _i9.Future<void> call(String? uid, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [uid, id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i14.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> register(
    String? email,
    String? password,
    String? name,
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, name, phone]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhotoBase64(String? base64) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoBase64, [base64]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateProfile({
    required String? name,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#name: name, #phone: phone}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> loadUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadUser, [uid]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserEntity extends _i1.Mock implements _i3.UserEntity {
  MockUserEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i16.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get phoneNumber =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumber),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumber),
            ),
          )
          as String);

  @override
  String get role =>
      (super.noSuchMethod(
            Invocation.getter(#role),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#role),
            ),
          )
          as String);

  @override
  _i3.UserEntity copyWith({
    String? name,
    String? phoneNumber,
    String? photoPath,
    String? photoBase64,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #name: name,
              #phoneNumber: phoneNumber,
              #photoPath: photoPath,
              #photoBase64: photoBase64,
            }),
            returnValue: _FakeUserEntity_1(
              this,
              Invocation.method(#copyWith, [], {
                #name: name,
                #phoneNumber: phoneNumber,
                #photoPath: photoPath,
                #photoBase64: photoBase64,
              }),
            ),
          )
          as _i3.UserEntity);
}

/// A class which mocks [GetTipsKesehatan].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTipsKesehatan extends _i1.Mock implements _i17.GetTipsKesehatan {
  MockGetTipsKesehatan() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TipsKesehatanRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTipsKesehatanRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TipsKesehatanRepository);

  @override
  _i9.Future<List<_i5.TipsKesehatanEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i9.Future<List<_i5.TipsKesehatanEntity>>.value(
              <_i5.TipsKesehatanEntity>[],
            ),
          )
          as _i9.Future<List<_i5.TipsKesehatanEntity>>);
}

/// A class which mocks [GetTipsKesehatanDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTipsKesehatanDetail extends _i1.Mock
    implements _i18.GetTipsKesehatanDetail {
  MockGetTipsKesehatanDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TipsKesehatanRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTipsKesehatanRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.TipsKesehatanRepository);

  @override
  _i9.Future<_i5.TipsKesehatanEntity> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i9.Future<_i5.TipsKesehatanEntity>.value(
              _FakeTipsKesehatanEntity_3(this, Invocation.method(#call, [id])),
            ),
          )
          as _i9.Future<_i5.TipsKesehatanEntity>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i19.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i9.Future<_i3.UserEntity> call(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, password]),
            returnValue: _i9.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#call, [email, password]),
              ),
            ),
          )
          as _i9.Future<_i3.UserEntity>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i20.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i9.Future<_i3.UserEntity> call(
    String? email,
    String? password,
    String? name,
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, password, name, phone]),
            returnValue: _i9.Future<_i3.UserEntity>.value(
              _FakeUserEntity_1(
                this,
                Invocation.method(#call, [email, password, name, phone]),
              ),
            ),
          )
          as _i9.Future<_i3.UserEntity>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i21.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i9.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [UpdatePhotoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePhotoUseCase extends _i1.Mock
    implements _i22.UpdatePhotoUseCase {
  MockUpdatePhotoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i9.Future<void> call(String? uid, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#call, [uid, path]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [FirebaseAuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthDatasource extends _i1.Mock
    implements _i23.FirebaseAuthDatasource {
  MockFirebaseAuthDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String formatPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#formatPhone, [phone]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#formatPhone, [phone]),
            ),
          )
          as String);

  @override
  _i9.Future<_i7.UserModel> register(
    String? email,
    String? password,
    String? name,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, name, phoneNumber]),
            returnValue: _i9.Future<_i7.UserModel>.value(
              _FakeUserModel_5(
                this,
                Invocation.method(#register, [
                  email,
                  password,
                  name,
                  phoneNumber,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.UserModel>);

  @override
  _i9.Future<void> updateUserProfile({
    required String? uid,
    required String? name,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #uid: uid,
              #name: name,
              #phone: phone,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserModel> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i9.Future<_i7.UserModel>.value(
              _FakeUserModel_5(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i9.Future<_i7.UserModel>);

  @override
  _i9.Future<void> updatePhotoBase64({
    required String? uid,
    required String? base64,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoBase64, [], {
              #uid: uid,
              #base64: base64,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhotoPath(String? uid, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoPath, [uid, path]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<dynamic> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<dynamic>.value(),
          )
          as _i9.Future<dynamic>);
}
