// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE3gMiacnTWo8OdbgQ3aKjLD7l6LMLqn4',
    appId: '1:1087211735712:web:6fbadacaadb2b06f8a57c5',
    messagingSenderId: '1087211735712',
    projectId: 'e-healty-4d587',
    authDomain: 'e-healty-4d587.firebaseapp.com',
    storageBucket: 'e-healty-4d587.firebasestorage.app',
    measurementId: 'G-HHY0VNQWQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsah9W8qvSCWG-KVVIcGebV3JSC5IkEZM',
    appId: '1:1087211735712:android:b2e18d8448406fbc8a57c5',
    messagingSenderId: '1087211735712',
    projectId: 'e-healty-4d587',
    storageBucket: 'e-healty-4d587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4K6I9ZvemqRZM_vJejCL1UDuSWOvMIic',
    appId: '1:1087211735712:ios:8daae07df867bc188a57c5',
    messagingSenderId: '1087211735712',
    projectId: 'e-healty-4d587',
    storageBucket: 'e-healty-4d587.firebasestorage.app',
    iosBundleId: 'com.example.eHealty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4K6I9ZvemqRZM_vJejCL1UDuSWOvMIic',
    appId: '1:1087211735712:ios:8daae07df867bc188a57c5',
    messagingSenderId: '1087211735712',
    projectId: 'e-healty-4d587',
    storageBucket: 'e-healty-4d587.firebasestorage.app',
    iosBundleId: 'com.example.eHealty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE3gMiacnTWo8OdbgQ3aKjLD7l6LMLqn4',
    appId: '1:1087211735712:web:48aedc65a5fca7ce8a57c5',
    messagingSenderId: '1087211735712',
    projectId: 'e-healty-4d587',
    authDomain: 'e-healty-4d587.firebaseapp.com',
    storageBucket: 'e-healty-4d587.firebasestorage.app',
    measurementId: 'G-K0RJPQ7E8G',
  );
}
